### ISSUE TITLE
Incompatible types error when using general Number type in variable assigning in strongly typed mode

### ISSUE THREAD

**Issue by raipc** [mvel/mvel#166]
```java
@Test
public void testInferNumberType() {
	final ParserContext parserContext = ParserContext.create().stronglyTyped();
	for (Method method : Context.class.getDeclaredMethods()) {
		parserContext.addImport(method.getName(), method);
	}
	final Class resultType = MVEL.analyze("var v = avg() / metric_value('m1');\nv > 0", parserContext);
	assertEquals(Boolean.class, resultType);
}

private interface Context {
	Number metric_value(String metric);
	double avg();
}
```

Error: 

```
[Error: [Error: incompatible types in statement: class java.lang.Number (compared from: double)]
[Near : {... var v = avg() / metric_value('m1'); ....}]
                     ^
[Line: 1, Column: 9]]
[Near : {... var v = avg() / metric_value('m1'); ....}]
                             ^
[Line: 1, Column: 17]

	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:298)
	at org.mvel2.util.ParseTools.subCompileExpression(ParseTools.java:2083)
	at org.mvel2.ast.AssignmentNode.<init>(AssignmentNode.java:70)
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:861)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:126)
	at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:67)
	at org.mvel2.MVEL.analyze(MVEL.java:680)
	at org.mvel2.MVEL.analyze(MVEL.java:685)
```

The expression compiles if I change strong typing with strict type enforcement, or modify `metric_value` return value to implementation, e.g. `BigDecimal`. Also the expression assigned to a variable compiles separately and returns correct type java.lang.Double.
